/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BoardsRouteImport } from './routes/boards'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContractRouteImport } from './routes/contract'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PathRouteImport } from './routes/path'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RedditRouteImport } from './routes/reddit'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ScamsRouteImport } from './routes/scams'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as DocumentsIndexRouteImport } from './routes/documents.index'
import { Route as DocumentsEditorFileIdRouteImport } from './routes/documents.editor.$fileId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsRoute = BoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractRoute = ContractRouteImport.update({
  id: '/contract',
  path: '/contract',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PathRoute = PathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RedditRoute = RedditRouteImport.update({
  id: '/reddit',
  path: '/reddit',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ScamsRoute = ScamsRouteImport.update({
  id: '/scams',
  path: '/scams',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocumentsRoute,
} as any)
const DocumentsEditorFileIdRoute = DocumentsEditorFileIdRouteImport.update({
  id: '/editor/$fileId',
  path: '/editor/$fileId',
  getParentRoute: () => DocumentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/boards': typeof BoardsRoute
  '/contact': typeof ContactRoute
  '/contract': typeof ContractRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/faq': typeof FaqRoute
  '/path': typeof PathRoute
  '/privacy': typeof PrivacyRoute
  '/reddit': typeof RedditRoute
  '/research': typeof ResearchRoute
  '/roles': typeof RolesRoute
  '/scams': typeof ScamsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/terms': typeof TermsRoute
  '/documents/': typeof DocumentsIndexRoute
  '/documents/editor/$fileId': typeof DocumentsEditorFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/boards': typeof BoardsRoute
  '/contact': typeof ContactRoute
  '/contract': typeof ContractRoute
  '/faq': typeof FaqRoute
  '/path': typeof PathRoute
  '/privacy': typeof PrivacyRoute
  '/reddit': typeof RedditRoute
  '/research': typeof ResearchRoute
  '/roles': typeof RolesRoute
  '/scams': typeof ScamsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/terms': typeof TermsRoute
  '/documents': typeof DocumentsIndexRoute
  '/documents/editor/$fileId': typeof DocumentsEditorFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/boards': typeof BoardsRoute
  '/contact': typeof ContactRoute
  '/contract': typeof ContractRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/faq': typeof FaqRoute
  '/path': typeof PathRoute
  '/privacy': typeof PrivacyRoute
  '/reddit': typeof RedditRoute
  '/research': typeof ResearchRoute
  '/roles': typeof RolesRoute
  '/scams': typeof ScamsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/terms': typeof TermsRoute
  '/documents/': typeof DocumentsIndexRoute
  '/documents/editor/$fileId': typeof DocumentsEditorFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/boards'
    | '/contact'
    | '/contract'
    | '/documents'
    | '/faq'
    | '/path'
    | '/privacy'
    | '/reddit'
    | '/research'
    | '/roles'
    | '/scams'
    | '/sitemap.xml'
    | '/sources'
    | '/terms'
    | '/documents/'
    | '/documents/editor/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/boards'
    | '/contact'
    | '/contract'
    | '/faq'
    | '/path'
    | '/privacy'
    | '/reddit'
    | '/research'
    | '/roles'
    | '/scams'
    | '/sitemap.xml'
    | '/sources'
    | '/terms'
    | '/documents'
    | '/documents/editor/$fileId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/boards'
    | '/contact'
    | '/contract'
    | '/documents'
    | '/faq'
    | '/path'
    | '/privacy'
    | '/reddit'
    | '/research'
    | '/roles'
    | '/scams'
    | '/sitemap.xml'
    | '/sources'
    | '/terms'
    | '/documents/'
    | '/documents/editor/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BoardsRoute: typeof BoardsRoute
  ContactRoute: typeof ContactRoute
  ContractRoute: typeof ContractRoute
  DocumentsRoute: typeof DocumentsRouteWithChildren
  FaqRoute: typeof FaqRoute
  PathRoute: typeof PathRoute
  PrivacyRoute: typeof PrivacyRoute
  RedditRoute: typeof RedditRoute
  ResearchRoute: typeof ResearchRoute
  RolesRoute: typeof RolesRoute
  ScamsRoute: typeof ScamsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SourcesRoute: typeof SourcesRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards': {
      id: '/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract': {
      id: '/contract'
      path: '/contract'
      fullPath: '/contract'
      preLoaderRoute: typeof ContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path': {
      id: '/path'
      path: '/path'
      fullPath: '/path'
      preLoaderRoute: typeof PathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reddit': {
      id: '/reddit'
      path: '/reddit'
      fullPath: '/reddit'
      preLoaderRoute: typeof RedditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scams': {
      id: '/scams'
      path: '/scams'
      fullPath: '/scams'
      preLoaderRoute: typeof ScamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/documents/editor/$fileId': {
      id: '/documents/editor/$fileId'
      path: '/editor/$fileId'
      fullPath: '/documents/editor/$fileId'
      preLoaderRoute: typeof DocumentsEditorFileIdRouteImport
      parentRoute: typeof DocumentsRoute
    }
  }
}

interface DocumentsRouteChildren {
  DocumentsIndexRoute: typeof DocumentsIndexRoute
  DocumentsEditorFileIdRoute: typeof DocumentsEditorFileIdRoute
}

const DocumentsRouteChildren: DocumentsRouteChildren = {
  DocumentsIndexRoute: DocumentsIndexRoute,
  DocumentsEditorFileIdRoute: DocumentsEditorFileIdRoute,
}

const DocumentsRouteWithChildren = DocumentsRoute._addFileChildren(
  DocumentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BoardsRoute: BoardsRoute,
  ContactRoute: ContactRoute,
  ContractRoute: ContractRoute,
  DocumentsRoute: DocumentsRouteWithChildren,
  FaqRoute: FaqRoute,
  PathRoute: PathRoute,
  PrivacyRoute: PrivacyRoute,
  RedditRoute: RedditRoute,
  ResearchRoute: ResearchRoute,
  RolesRoute: RolesRoute,
  ScamsRoute: ScamsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SourcesRoute: SourcesRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
